version: '3'

services:
  node_app:
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - .:/app
    ports:
      - "${NODE_APP_PORT}:3000"
    command: npm run dev

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
    ports:
      - 8081:8080
    networks:
      - ebookjs-net
