version: '3'

services:
  node_app:
    environment:
      DB_HOST: mysql_db
    volumes:
      - .:/app
    ports:
      - '${NODE_APP_PORT}:3000'
    command: npm run dev

  mysql_db_test:
    image: mysql
    ports:
      - '${DB_TEST_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_TEST_USER}
      MYSQL_PASSWORD: ${DB_TEST_PASSWORD}
      MYSQL_DATABASE: ${DB_TEST_DATABASE}
    volumes:
      - mysql_test:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - ebookjs-net

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
    ports:
      - '8081:8080'
    networks:
      - ebookjs-net

volumes:
  mysql_test:
