version: '3'

services:
  node_app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    depends_on:
      - mysql_db
    networks:
      - ebookjs-net

  mysql_db:
    image: mysql
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - ebookjs-net

networks:
  ebookjs-net:

volumes:
  mysql:
