# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: e-bookJS CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_USER=ebookjs_test -e MYSQL_PASSWORD=ebookjs_test -e MYSQL_DATABASE=ebookjs_dbtest --entrypoint sh mysql:8 -c "exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"
        ports:
          - 3306:3306

      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run npm install
        run: npm install

      - name: Create .env file
        run: |
          touch .env
          echo DB_DIALECT=mysql >> .env
          echo DB_TEST_HOST=127.0.0.1 >> .env
          echo DB_TEST_USER='ebookjs_test' >> .env
          echo DB_TEST_PASSWORD='ebookjs_test' >> .env
          echo DB_TEST_DATABASE='ebookjs_dbtest' >> .env
          echo REDIS_HOST_TEST='127.0.0.1' >> .env
          echo REDIS_PORT_TEST='6379' >> .env
          cat .env

      - name: Run linter
        run: npm run lint

      - name: Run Migration
        run: npm run migrate:test

      - name: Run npm test
        run: npm run test

      - name: Run npm build
        run: npm run build --if-present
