# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: e-bookJS CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run npm install
        run: npm install

      - name: Create .env file
        run: |
          touch .env
          echo TEST_DB_HOST=0.0.0.0 >> .env
          echo TEST_DB_USER='ebookjs_test' >> .env
          echo TEST_DB_PASSWORD='ebookjs_test' >> .env
          echo TEST_DB_DATABASE='ebookjs_dbtest' >> .env
          cat .env
          
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ebookjs_dbtest;' -u ebookjs_test -p ebookjs_test

      - name: Run npm test
        run: npm run ci_test

      - name: Run npm build
        run: npm run build --if-present
